### ISSUE TITLE
tinyhttp doesn't work as server for Next.js

### ISSUE THREAD

**Issue by vitalybaev** [talentlessguy/tinyhttp#184]
**Describe the bug**

I often use Next.js framework. It commonly used with Express server. I've got an idea to try tinyhttp for my projects (and also to add an example to Next.js repo).
But I've got some errors and maybe you could tell me what is wrong. I'll also continue investigate this issue as well.

Error log: 
```
➜  next-tinyhttp yarn dev
yarn run v1.22.5
$ node server.js
event - compiled successfully
> Ready on http://localhost:3000
(node:38326) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at /Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:34:97
    at Array.find (<anonymous>)
    at getRouteFromApp (/Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:34:58)
    at /Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:298:39
    at loop (/Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:324:34)
    at /Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:308:21
    at loop (/Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:324:34)
    at /Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:308:21
    at loop (/Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:324:34)
    at /Users/vitalybaev/Documents/OpenSource/next-tinyhttp/node_modules/@tinyhttp/app/dist/index.cjs:308:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:38326) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:38326) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**

1. Clone https://github.com/vitalybaev/next-tinyhttp
2. `yarn`
3. `yarn dev`, wait for ready message
4. Open browser and navigate to the root
5. But routes `/a` and `/b` works well

**Expected behavior**

Server works fine, especially because tinyhttp aims to be a Express-like server.
You could see several custom server examples in Next.js repository (https://github.com/vercel/next.js/tree/canary/examples), directory starts with `custom-server-*`

**Versions**

* `node`: 14.9.0
* `@tinyhttp/app`: 0.5.11

**Additional context**

**Comment by talentlessguy** [comment]
Found the root of the problem, `req.route` crashes, so the whole thing crashes

fixing this now

**Comment by talentlessguy** [comment]
added this:

```js
  server.get('/', (req, res) => {
      return app.render(req, res, '/', req.query)
    })
```

and it doesn't crash anymore

but all of the rendered pages are empty for some reason

**Comment by talentlessguy** [comment]
ok i found out the problem

`server.all('*')` wasn't catching any routes


try using `server.use((req, res) => handle(req, res))` instead

**Comment by talentlessguy** [comment]
Fixed `server.use` in `0.5.12`

try now with:

```sh
pnpm i @tinyhttp/app@0.5.12
```

**Comment by talentlessguy** [comment]
@all-contributors add @vitalybaev for bug
