### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: h is not a function

### ISSUE THREAD

**Issue by creepinson** [talentlessguy/tinyhttp#202]
**Describe the bug**

I tried to use socket.io and compression middleware but even after removing compression it gives this error upon trying to browse to the server url.

**To Reproduce**

1. ... use socket.io with `const server = app.listen(3000)`
2. ... compression middleware

**Expected behavior**

To load the page fine (serving html)

**Versions**

* `node`: 14
* `@tinyhttp/app`: 1.0.14

**Additional context**

**Comment by creepinson** [comment]
Full error:
```
[0] (node:42224) UnhandledPromiseRejectionWarning: TypeError: h is not a function
   at B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\@tinyhttp\app@1.0.14\node_modules\@tinyhttp\app\dist\index.cjs:140:9
[0]     at B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\@tinyhttp\app@1.0.14\node_modules\@tinyhttp\app\dist\index.cjs:277:44
[0]     at loop (B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\@tinyhttp\app@1.0.14\node_modules\@tinyhttp\app\dist\index.cjs:286:34)
[0]     at App.handler (B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\@tinyhttp\app@1.0.14\node_modules\@tinyhttp\app\dist\index.cjs:290:9)
[0]     at Server.<anonymous> (B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\@tinyhttp\app@1.0.14\node_modules\@tinyhttp\app\dist\index.cjs:300:49)
[0]     at Server.<anonymous> (B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\engine.io@4.0.5\node_modules\engine.io\lib\server.js:411:24)
[0]     at Server.<anonymous> (B:\Essentials\Projects\Programming\docker-dashboard-example\node_modules\.pnpm\socket.io@3.0.4\node_modules\socket.io\dist\index.js:193:28)
[0]     at Server.emit (events.js:315:20)
[0]     at parserOnIncoming (_http_server.js:874:12)

```

**Comment by creepinson** [comment]
OOps, turns out I forgot paraentheses on my app.use

```
app.use(cors)
```
and i should ahve done
```
app.use(cors())
```
