### ISSUE TITLE
UnhandledPromiseRejectionWarning when creating a new project.

### ISSUE THREAD

**Issue by fthebaud** [talentlessguy/tinyhttp#262]
*UnhandledPromiseRejectionWarning* when creating a new project.

```
╰─ tinyhttp new basic my-app     
Creating a new tinyhttp project from basic template in my-app folder ⚡
Fetching template contents ⌛
(node:19015) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at installPackages (file:///home/fthebaud/.nvm/versions/node/v14.15.1/pnpm-global/5/node_modules/.pnpm/@tinyhttp+cli@1.3.1/node_modules/@tinyhttp/cli/dist/index.js:63:85)
    at CAC.<anonymous> (file:///home/fthebaud/.nvm/versions/node/v14.15.1/pnpm-global/5/node_modules/.pnpm/@tinyhttp+cli@1.3.1/node_modules/@tinyhttp/cli/dist/index.js:221:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the behavior:**
`pnpm i -g @tinyhttp/cli`
`tinyhttp new basic my-app`

**Versions**
`@tinyhttp/cli 1.3.1`
`node v14.15.1`

**Comment by talentlessguy** [comment]
this was already fixed in https://github.com/talentlessguy/tinyhttp/issues/259 and sorry that i forgot to release a new version (more like forgot to run build command) :(

try now with `1.3.2` please

**Comment by fthebaud** [comment]
@talentlessguy, it's working in 1.3.2. 
Thank you!
